import type { Metadata } from "next";
import { FacilityRegister } from "@/components/FacilityRegister";
import { ImagePanel, ProjectCTA, SectionHeader, SystemLabel } from "@/components/System";

export const metadata: Metadata = { title: "About Moist Corp | Apparel Production Infrastructure", description: "The Moist Corp operating model: coordinated development, sourcing, manufacturing, quality assurance and logistics from Greater Noida, India.", alternates: { canonical: "/about" }, openGraph: { title: "About Moist Corp | Apparel Production Infrastructure", description: "A different apparel production model, built for control.", url: "/about", images: ["/factory-1.jpg"], type: "website" } };
const principles = [["01", "Precision", "Clear specifications, agreed parameters and repeatable production processes."], ["02", "Visibility", "Production status and changes communicated before they become business problems."], ["03", "Velocity", "Shorter development and production cycles help brands act closer to demand."], ["04", "Accountability", "One team coordinates every handoff across the production sequence."], ["05", "Scalability", "A 50-piece starting MOQ creates a practical path from testing to volume."]];

export default function AboutPage() { return <main id="main-content">
  <section className="page-hero grid-light"><div className="container page-hero-grid"><div><SystemLabel>CORPORATE FILE / MC-001</SystemLabel><h1>A DIFFERENT<br />PRODUCTION<br />MODEL.</h1><p>Apparel brands need more than a factory. They need a production system with the visibility and discipline to keep development, manufacturing and delivery aligned.</p></div><ImagePanel src="/factory-1.jpg" alt="Moist Corp manufacturing facility" code="MC / CORPORATE RECORD" caption="PRODUCTION FACILITY / OPERATIONS" priority /></div></section>
  <section className="section narrative"><div className="container"><SectionHeader index="01" label="OPERATING MODEL" title={<>BUILT AGAINST<br />FRAGMENTATION.</>} /><div className="narrative-grid"><p className="lead">Traditional apparel production asks brands to coordinate too many disconnected parties—with limited visibility and timelines that are difficult to control.</p><div><p>Long lead times force brands to commit inventory before demand is clear. High minimums increase that exposure. When materials, sampling, production and logistics are handled separately, every handoff adds delay and ambiguity.</p><p>Moist Corp was built to reduce those variables. We coordinate product development, sourcing, sampling, manufacturing, quality assurance and logistics as one production system.</p><p>From Greater Noida, we support independent labels, emerging designers and growing apparel businesses with a 50-piece starting MOQ, production cycles under 35 days and a 98% on-time delivery rate.</p></div></div></div></section>
  <section className="section principles grid-dark"><div className="container"><SectionHeader light index="02" label="CORPORATE PRINCIPLES" title="OPERATING CODE." /><div className="principle-grid">{principles.map(([id,title,copy]) => <article key={id}><span>{id}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="section"><div className="container"><SectionHeader index="03" label="PRODUCTION ECOSYSTEM" title={<>ONE TEAM.<br />EVERY HANDOFF.</>} copy="Specialist production partners, internal oversight and a defined quality system operate as one coordinated structure." /><div className="capability-list">{["Product development", "Fabric & trim sourcing", "Sampling", "Manufacturing", "Quality assurance", "Logistics"].map((item,i)=><div key={item}><span>0{i+1}</span><h3>{item}</h3></div>)}</div></div></section><FacilityRegister /><ProjectCTA />
</main>; }
